GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthdHJpbmUgRmluc3RhZCIsImlhdCI6MTczNzQ5MDg4OCwiZXhwIjoxNzM3NDkxNzg4fQ.jQ0EGJcPJF9Dqv-FG0WgZJDw9OovfkLM8yDcbFEpjiU
###
GET http://localhost:3000/movies/678ebbc58b76372753abaa7a

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Katrine Finstad",
    "password": "12345678"
}

###
POST http://localhost:3000/refresh
Content-Type: application/json

{
  "token":
          "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthdHJpbmUgRmluc3RhZCIsImlhdCI6MTczNzQ5MTYxMn0.3fiTXHR-b96B0KwuASJpcdUzl2WduCBqkZl8e6ZHwSQ"
}

###
PUT http://localhost:3000/movies/678ebbc58b76372753abaa7a
Content-Type: application/json

{
  "title": "",
  "year": null,
  "category": "",
  "director": {
    "name": " fenris finstad",
    "gender": "female"
  }
}


###
DELETE http://localhost:3000/movies/678e83af03e0cd23d8952429