GET http://localhost:3000/movies?director=Panida%20Paethanom


###
GET http://localhost:3000/movies/678ebbc58b76372753abaa7a

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "test1",
    "password": "12345678"
}

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "token":
          "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthdHJpbmUgRmluc3RhZCIsImlhdCI6MTczNzU0NTY0N30.97SaEhWnbaWY57dc3zfcKqEuCEns55jiVJtutKLFIqk"
}

###
PUT http://localhost:3000/movies/678ebbc58b76372753abaa7a
Content-Type: application/json

{
  "title": "",
  "year": null,
  "category": "",
  "director": {
    "name": " fenris finstad",
    "gender": "female"
  }
}


###
DELETE http://localhost:3000/movies/678e83af03e0cd23d8952429